server:
    interface: 0.0.0.0
    interface: fd00::200

    access-control: 192.168.0.0/16 allow
    access-control: fd00::/8 allow

    port: 5335
    verbosity: 0
    log-queries: no
    log-replies: no

    do-ip4: yes
    do-ip6: yes
    do-udp: yes
    do-tcp: yes
    prefer-ip6: no

    edns-buffer-size: 1232
    max-udp-size: 1232

    num-threads: 8
    so-reuseport: yes

    num-queries-per-thread: 8192
    outgoing-range: 16384

    msg-cache-size: 1g
    rrset-cache-size: 2g
    key-cache-size: 512m
    neg-cache-size: 256m

    msg-cache-slabs: 8
    rrset-cache-slabs: 8
    infra-cache-slabs: 8
    key-cache-slabs: 8

    infra-cache-numhosts: 50000

    cache-min-ttl: 300
    cache-max-ttl: 86400

    prefetch: yes
    prefetch-key: yes

    aggressive-nsec: yes
    rrset-roundrobin: yes

    qname-minimisation: yes
    qname-minimisation-strict: no

    tcp-upstream: no
    outgoing-num-tcp: 40
    incoming-num-tcp: 40

    so-rcvbuf: 32m
    so-sndbuf: 32m

    unwanted-reply-threshold: 10000

    hide-identity: yes
    hide-version: yes

    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-below-nxdomain: yes

    serve-expired: yes
    serve-expired-ttl: 86400
    serve-expired-reply-ttl: 30
    serve-expired-client-timeout: 1800

    minimal-responses: yes

    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-domain: "xterax.de"
    private-domain: "home-assist.xterax.de"
    private-domain: "jelly.xterax.de"
    private-domain: "portainer.xterax.de"
    private-domain: "gm.xterax.de"

    local-zone: "xterax.de." static
    local-data: "xterax.de. IN A 192.168.179.200"
    local-data: "xterax.de. IN AAAA fd00::200"
    local-data: "home-assist.xterax.de. IN AAAA fd00::200"
    local-data: "home-assist.xterax.de. IN A 192.168.179.200"
    local-data: "jelly.xterax.de. IN A 192.168.179.200"
    local-data: "jelly.xterax.de. IN AAAA fd00::200"
    local-data: "portainer.xterax.de. IN A 192.168.179.200"
    local-data: "gm.xterax.de. IN A 192.168.179.200"
    local-data: "gm.xterax.de. IN AAAA fd00::200"
    local-data: "portainer.xterax.de. IN AAAA fd00::200"
    local-data: "fritz.box. IN A 192.168.179.1"
    local-data: "fritz.box. IN AAAA fd00::b6fc:7dff:fe12:b1f2"
    local-data: "wizard.xterax.de. IN AAAA fd00::200"
    local-data: "wizard.xterax.de. IN A 192.168.179.200"
    local-data: "pihole.xterax.de. IN AAAA fd00::200"
    local-data: "pihole.xterax.de. IN A 192.168.179.200"
    local-data: "_ts3._udp.gm.xterax.de. 0 IN SRV 0 0 9987 gm.xterax.de."
